parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     didierio_connect
    database_user:     root
    database_password: ~

    secret: ThisTokenIsNotSoSecretChangeIt
    locale: en
